services:
  web-service:
    build: ./WebService
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://niksignjar_db_user:2lLWNURcOZyYsJKA@virtualestate.ha8dxw2.mongodb.net/VirtualEstate?retryWrites=true&w=majority&appName=VirtualEstate
    restart: always
    networks:
      - app-network

  web-client:
    build: ./WebClient
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - web-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge