package com.example.desktopapplication

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.desktopapplication.models.Property

@Composable
fun GeneratorScreen(onSendToDatabase: (List<Property>) -> Unit) {
    var count by remember { mutableStateOf("10") }
    var priceMin by remember { mutableStateOf("50000") }
    var priceMax by remember { mutableStateOf("500000") }
    var sizeMin by remember { mutableStateOf("30") }
    var sizeMax by remember { mutableStateOf("200") }

    var generated by remember { mutableStateOf<List<Property>>(emptyList()) }
    var selectedIds by remember { mutableStateOf<Set<Int>>(emptySet()) }
    var page by remember { mutableStateOf(0) }
    var sortKey by remember { mutableStateOf<String?>(null) }
    var sortDir by remember { mutableStateOf(SortDirection.ASC) }

    var filterText by remember { mutableStateOf("") }
    var filterType by remember { mutableStateOf("") }
    var filterOffer by remember { mutableStateOf("") }

    val filtered = remember(generated, filterText, filterType, filterOffer, sortKey, sortDir) {
        val q = filterText.trim()
        val result = generated.filter { p ->
            val textOk = q.isBlank() || listOf(p.region, p.city, p.neighborhood).any { it.contains(q, ignoreCase = true) }
            val typeOk = filterType.isBlank() || p.propertyType.contains(filterType, ignoreCase = true)
            val offerOk = filterOffer.isBlank() || p.offerType == filterOffer
            textOk && typeOk && offerOk
        }
        val sorted = when (sortKey) {
            "region" -> result.sortedBy { it.region.lowercase() }
            "city" -> result.sortedBy { (if (it.neighborhood.isNotBlank()) it.neighborhood else it.city).lowercase() }
            "propertyType" -> result.sortedBy { it.propertyType.lowercase() }
            "offerType" -> result.sortedBy { it.offerType.lowercase() }
            "size" -> result.sortedBy { it.size }
            "price" -> result.sortedBy { it.price }
            else -> result
        }
        if (sortKey != null && sortDir == SortDirection.DESC) sorted.reversed() else sorted
    }
    val totalPages = ((filtered.size - 1) / PAGE_SIZE + 1).coerceAtLeast(1)
    val currentPage = page.coerceIn(0, totalPages - 1)
    val paged = filtered.drop(currentPage * PAGE_SIZE).take(PAGE_SIZE)
    val sortClick: (String) -> Unit = { k ->
        val (newKey, newDir) = nextSort(sortKey, sortDir, k); sortKey = newKey; sortDir = newDir
    }

    LaunchedEffect(filterText, filterType, filterOffer) { selectedIds = emptySet() }

    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
        Card(elevation = 4.dp) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                Text("Parametri generiranja", fontWeight = FontWeight.Bold)
                StyledTextField(count, { count = it }, "Število zapisov")
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    StyledTextField(priceMin, { priceMin = it }, "Cena min (€)", Modifier.weight(1f))
                    StyledTextField(priceMax, { priceMax = it }, "Cena max (€)", Modifier.weight(1f))
                }
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    StyledTextField(sizeMin, { sizeMin = it }, "Velikost min (m²)", Modifier.weight(1f))
                    StyledTextField(sizeMax, { sizeMax = it }, "Velikost max (m²)", Modifier.weight(1f))
                }
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    ActionButton(
                        text = "Generiraj",
                        onClick = {
                            generated = DataGenerator.generate(
                                count = count.toIntOrNull() ?: 10,
                                priceRange = (priceMin.toIntOrNull() ?: 50000)..(priceMax.toIntOrNull() ?: 500000),
                                sizeRange = (sizeMin.toIntOrNull() ?: 30)..(sizeMax.toIntOrNull() ?: 200)
                            )
                            selectedIds = generated.mapNotNull { it.id }.toSet()
                            page = 0
                        },
                        icon = Icons.Default.Casino
                    )
                    ActionButton(
                        text = "Pošlji v bazo (${selectedIds.size})",
                        onClick = {
                            onSendToDatabase(generated.filter { it.id in selectedIds })
                            generated = emptyList()
                            selectedIds = emptySet()
                        },
                        color = Color(0xFF27AE60),
                        icon = Icons.Default.Save,
                        enabled = selectedIds.isNotEmpty()
                    )
                }
            }
        }

        if (generated.isNotEmpty()) {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                StyledTextField(filterText, { filterText = it; page = 0 }, "Išči (regija, mesto)", Modifier.weight(2f))
                StyledTextField(filterType, { filterType = it; page = 0 }, "Tip", Modifier.weight(1f))
                Box(modifier = Modifier.weight(1f)) {
                    DropdownSelector("Ponudba (vse)", filterOffer.ifBlank { "vse" }, listOf("vse") + OFFER_TYPES) {
                        filterOffer = if (it == "vse") "" else it; page = 0
                    }
                }
            }

            Card(elevation = 4.dp, modifier = Modifier.fillMaxWidth()) {
                Column {
                    Row(
                        modifier = Modifier.fillMaxWidth().background(Color(0xFFECF0F1)).padding(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        val allIds = filtered.mapNotNull { it.id }.toSet()
                        val allSelected = allIds.isNotEmpty() && allIds.all { it in selectedIds }
                        Checkbox(
                            checked = allSelected,
                            onCheckedChange = { c ->
                                selectedIds = if (c) selectedIds + allIds else selectedIds - allIds
                            },
                            modifier = Modifier.weight(0.3f)
                        )
                        SortableHeader("Regija", "region", sortKey, sortDir, sortClick, Modifier.weight(1f))
                        SortableHeader("Mesto / Naselje", "city", sortKey, sortDir, sortClick, Modifier.weight(2f))
                        SortableHeader("Tip", "propertyType", sortKey, sortDir, sortClick, Modifier.weight(1f))
                        SortableHeader("Ponudba", "offerType", sortKey, sortDir, sortClick, Modifier.weight(0.7f))
                        SortableHeader("m²", "size", sortKey, sortDir, sortClick, Modifier.weight(0.5f))
                        SortableHeader("Cena", "price", sortKey, sortDir, sortClick, Modifier.weight(1f))
                    }
                    Divider()
                    if (filtered.isEmpty()) {
                        Box(
                            modifier = Modifier.fillMaxWidth().padding(40.dp),
                            contentAlignment = Alignment.Center
                        ) { Text("Filter ne najde zadetkov.", color = Color(0xFF6B7280)) }
                    } else LazyColumn(modifier = Modifier.heightIn(max = 600.dp)) {
                        items(paged) { p ->
                            val checked = p.id in selectedIds
                            Row(
                                modifier = Modifier.fillMaxWidth().padding(12.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Checkbox(
                                    checked = checked,
                                    onCheckedChange = { c ->
                                        val id = p.id ?: return@Checkbox
                                        selectedIds = if (c) selectedIds + id else selectedIds - id
                                    },
                                    modifier = Modifier.weight(0.3f)
                                )
                                Text(p.region, modifier = Modifier.weight(1f))
                                Text(
                                    if (p.neighborhood.isNotBlank()) "${p.neighborhood}, ${p.city}" else p.city,
                                    modifier = Modifier.weight(2f)
                                )
                                Text(p.propertyType, modifier = Modifier.weight(1f))
                                Text(p.offerType, modifier = Modifier.weight(0.7f))
                                Text("${p.size.toInt()}", modifier = Modifier.weight(0.5f))
                                Text("${p.price.toInt()} €", modifier = Modifier.weight(1f))
                            }
                            Divider()
                        }
                    }
                }
            }

            if (filtered.isNotEmpty()) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("${filtered.size} zapisov · stran ${currentPage + 1} / $totalPages", color = Color(0xFF6B7280))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        ActionButton("‹ Prejšnja", { page = (currentPage - 1).coerceAtLeast(0) }, enabled = currentPage > 0)
                        ActionButton("Naslednja ›", { page = (currentPage + 1).coerceAtMost(totalPages - 1) }, enabled = currentPage < totalPages - 1)
                    }
                }
            }
        }
    }
}
